insert into public.ingredients (name, slug, description, category, image_url, storage_information, safety_information, status)
values
  ('Red lentils', 'red-lentils', 'Split red lentils soften quickly and thicken soups and stews.', 'Legumes', null, 'Keep dry lentils in a sealed container in a cool, dry cupboard.', 'Sort and rinse dry lentils before cooking; follow package directions and cook until tender.', 'published'),
  ('Green lentils', 'green-lentils', 'Green lentils hold their shape well when simmered gently.', 'Legumes', null, 'Keep dry lentils sealed in a cool, dry cupboard.', 'Sort and rinse dry lentils before cooking; cook until tender.', 'published'),
  ('Chickpeas', 'chickpeas', 'Chickpeas add a creamy texture and mild, nutty flavor to many dishes.', 'Legumes', null, 'Store dry chickpeas in a sealed cool, dry place; refrigerate opened canned chickpeas in a covered container.', 'Drain and rinse canned chickpeas with clean water; cook dried chickpeas fully.', 'published'),
  ('Dried pasta', 'dried-pasta', 'Dried wheat pasta cooks in salted water and pairs with many sauces.', 'Grains', null, 'Keep in its sealed package or an airtight container in a dry cupboard.', 'Check the package for wheat or other allergen information.', 'published'),
  ('Basmati rice', 'basmati-rice', 'Basmati is a long-grain rice known for a light, aromatic finish.', 'Grains', null, 'Store uncooked rice in a dry, sealed container.', 'Rinse if desired and cook using package guidance; refrigerate cooked rice promptly.', 'published'),
  ('Canned tomatoes', 'canned-tomatoes', 'Canned tomatoes provide a consistent base for sauces, stews, and braises.', 'Vegetables', null, 'Store unopened cans in a cool, dry cupboard; refrigerate leftovers in a covered container.', 'Discard leaking, bulging, or badly damaged cans.', 'published'),
  ('Ripe tomatoes', 'ripe-tomatoes', 'Fresh tomatoes bring acidity and juiciness to salads and cooked dishes.', 'Vegetables', null, 'Keep ripe tomatoes at room temperature for best texture; refrigerate cut tomatoes.', 'Wash under running water before cutting.', 'published'),
  ('Red onion', 'red-onion', 'Red onion is useful raw for sharpness and cooked for mellow sweetness.', 'Vegetables', null, 'Store whole onions in a cool, dry, ventilated place; refrigerate cut onion in a covered container.', 'Wash hands and cutting surfaces after handling produce.', 'published'),
  ('Garlic', 'garlic', 'Garlic contributes a savory aroma and can become bitter if scorched.', 'Aromatics', null, 'Store whole bulbs in a cool, dry place with airflow.', 'Use clean utensils and refrigerate prepared garlic mixtures promptly.', 'published'),
  ('Fresh ginger', 'fresh-ginger', 'Fresh ginger adds warm, citrusy aroma to sauces, soups, and stir-fries.', 'Aromatics', null, 'Refrigerate fresh ginger in a breathable bag or covered container.', 'Wash before peeling or cutting.', 'published'),
  ('Red bell pepper', 'red-bell-pepper', 'Red bell pepper adds sweetness, color, and a crisp bite.', 'Vegetables', null, 'Refrigerate whole peppers and use cut pepper within a few days.', 'Wash under running water before cutting.', 'published'),
  ('Baby spinach', 'baby-spinach', 'Tender spinach wilts quickly and works in soups, curries, and egg dishes.', 'Vegetables', null, 'Keep refrigerated and follow the package use-by guidance.', 'Wash loose leaves under running water; follow package instructions for ready-to-eat greens.', 'published'),
  ('Eggs', 'eggs', 'Eggs set into a tender protein-rich curd when gently cooked.', 'Protein', null, 'Keep eggs refrigerated in their carton.', 'Keep eggs refrigerated and cook until whites and yolks are firm unless using pasteurized eggs in a preparation that remains raw.', 'published'),
  ('Chicken thighs', 'chicken-thighs', 'Chicken thighs stay moist when cooked thoroughly and suit quick sautés or braises.', 'Poultry', null, 'Keep raw chicken refrigerated at 4 C / 40 F or below and separate from ready-to-eat food.', 'Use separate utensils and surfaces for raw poultry; cook to 74 C / 165 F measured with a food thermometer.', 'published'),
  ('Olive oil', 'olive-oil', 'Olive oil carries aromas and helps ingredients cook evenly.', 'Pantry', null, 'Store tightly closed away from heat and direct light.', 'Avoid leaving hot oil unattended; keep water away from hot oil.', 'published'),
  ('Ground cumin', 'ground-cumin', 'Cumin has an earthy aroma and is used in many regional cooking traditions.', 'Spices', null, 'Keep sealed in a cool, dry cupboard.', 'Use clean, dry utensils to prevent moisture entering the container.', 'published'),
  ('Berbere spice blend', 'berbere-spice-blend', 'Berbere is a complex Ethiopian spice blend whose ingredients and heat vary by maker and region.', 'Spices', null, 'Keep sealed in a cool, dry cupboard away from direct sunlight.', 'Check the ingredient label for allergens and chili heat before serving.', 'published'),
  ('Lemons', 'lemons', 'Lemon juice and zest add bright acidity to savory dishes.', 'Fruit', null, 'Store whole lemons refrigerated for longer keeping; refrigerate cut lemon.', 'Wash the peel before zesting.', 'published'),
  ('Courgette', 'courgette', 'Courgette softens quickly and takes on the flavor of herbs and sauces.', 'Vegetables', null, 'Refrigerate unwashed courgette and wash before preparation.', 'Wash under running water before cutting.', 'published'),
  ('Fresh basil', 'fresh-basil', 'Fresh basil has a sweet, aromatic flavor and is best added near the end of cooking.', 'Herbs', null, 'Keep stems in a glass of water at room temperature or refrigerate loosely wrapped.', 'Wash herbs under running water before use.', 'published'),
  ('Coconut milk', 'coconut-milk', 'Coconut milk adds body and a gentle coconut flavor to curries and soups.', 'Pantry', null, 'Store unopened cans in a cool, dry cupboard; refrigerate opened coconut milk in a covered container.', 'Check the can for damage and refrigerate leftovers promptly.', 'published'),
  ('Flat-leaf parsley', 'flat-leaf-parsley', 'Parsley adds a fresh, green finish to soups, salads, and stews.', 'Herbs', null, 'Refrigerate loosely wrapped and wash just before use.', 'Wash under running water before chopping.', 'published'),
  ('Soy sauce', 'soy-sauce', 'Soy sauce contributes salty, savory flavor to marinades and stir-fries.', 'Condiments', null, 'Refrigerate after opening if directed on the label.', 'Contains soy and often wheat; check the label for allergen information.', 'published'),
  ('Vegetable stock', 'vegetable-stock', 'Vegetable stock provides a savory cooking liquid for grains, soups, and legumes.', 'Pantry', null, 'Refrigerate opened stock and follow its package use-by instructions.', 'Bring stock to a simmer when using in hot dishes; refrigerate leftovers promptly.', 'published'),
  ('Carrots', 'carrots', 'Carrots contribute sweetness and texture to soups and braises.', 'Vegetables', null, 'Refrigerate in a produce drawer.', 'Wash under running water and scrub if needed before cutting.', 'published'),
  ('Hard cheese', 'hard-cheese', 'A small amount of hard cheese adds savory depth to vegetables and eggs.', 'Dairy', null, 'Keep refrigerated and follow the package use-by guidance.', 'Contains milk; use clean utensils and avoid leaving dairy at room temperature for extended periods.', 'published');

insert into public.recipes (
  title, slug, description, cuisine, category, difficulty, prep_time_minutes, cook_time_minutes,
  servings, image_url, educational_info, safety_notes, nutrition_info, status
)
values
  ('Ethiopian Misir Wat', 'ethiopian-misir-wat', 'Red lentils simmered with berbere, onion, and garlic until soft and deeply savory.', 'Ethiopian', 'Plant-based', 'intermediate', 15, 45, 4, '/images/misir-wat.jpg', 'Gentle simmering lets split red lentils soften and thicken the stew. Berbere blends vary by maker and household.', 'Keep dry ingredients and clean utensils separate from ready-to-eat foods. Refrigerate leftovers promptly.', '{"note":"No numeric nutrition estimate is provided; portions and brands vary. This content is educational, not medical advice."}', 'published'),
  ('Skillet Shakshuka', 'skillet-shakshuka', 'Eggs gently cooked in a spiced tomato and pepper sauce.', 'North African', 'Vegetarian', 'beginner', 10, 25, 3, '/images/shakshuka.jpg', 'Cooking the pepper and tomato base before adding eggs builds flavor and helps the sauce thicken.', 'Cook eggs until whites are fully set; use pasteurized eggs for preparations that remain raw.', '{"note":"No numeric nutrition estimate is provided; portions and brands vary. This content is educational, not medical advice."}', 'published'),
  ('Lemony Lentil Soup', 'lemony-lentil-soup', 'Green lentils, carrots, and aromatics finished with lemon and parsley.', 'Eastern Mediterranean-inspired', 'Plant-based', 'beginner', 15, 40, 4, '/images/lentil-soup.jpg', 'Acidity added near the end brightens the earthy flavor of lentils.', 'Bring soup to a simmer and refrigerate leftovers promptly in shallow covered containers.', '{"note":"No numeric nutrition estimate is provided; portions and brands vary. This content is educational, not medical advice."}', 'published'),
  ('Ginger Chicken Stir-fry', 'ginger-chicken-stir-fry', 'Chicken, crisp pepper, ginger, and garlic served with basmati rice.', 'East Asian-inspired', 'Quick meals', 'intermediate', 20, 20, 4, '/images/chicken-stir-fry.jpg', 'Preparing ingredients before heating the pan helps keep a stir-fry moving at high heat.', 'Keep raw chicken separate from ready-to-eat foods and cook it to 74 C / 165 F measured with a food thermometer.', '{"note":"No numeric nutrition estimate is provided; portions and brands vary. This content is educational, not medical advice."}', 'published'),
  ('Roasted Vegetable Pasta', 'roasted-vegetable-pasta', 'Pasta tossed with courgette, tomato, olive oil, and fresh basil.', 'Italian-inspired', 'Quick meals', 'beginner', 15, 30, 4, '/images/vegetable-pasta.jpg', 'Roasting vegetables in a single layer encourages browning rather than steaming.', 'Wash produce before cutting and follow package guidance for cooking pasta.', '{"note":"No numeric nutrition estimate is provided; portions and brands vary. This content is educational, not medical advice."}', 'published'),
  ('Coconut Chickpea Curry', 'coconut-chickpea-curry', 'Chickpeas and spinach simmered with tomato, cumin, and coconut milk.', 'South Asian-inspired', 'Plant-based', 'beginner', 15, 30, 4, '/images/vegetable-curry.jpg', 'Blooming ground spices briefly in warm oil can deepen their aroma; avoid scorching them.', 'Drain and rinse canned chickpeas with clean water and refrigerate opened ingredients promptly.', '{"note":"No numeric nutrition estimate is provided; portions and brands vary. This content is educational, not medical advice."}', 'published'),
  ('Green Lentil Herb Salad', 'green-lentil-herb-salad', 'Green lentils with tomato, onion, parsley, lemon, and olive oil.', 'Levantine-inspired', 'Plant-based', 'beginner', 15, 30, 4, '/images/lentil-soup.jpg', 'Lentils that hold their shape make a satisfying base for a dressed salad.', 'Cool cooked lentils promptly and keep the salad refrigerated until serving.', '{"note":"No numeric nutrition estimate is provided; portions and brands vary. This content is educational, not medical advice."}', 'published'),
  ('Tomato Chickpea Stew', 'tomato-chickpea-stew', 'Chickpeas simmered with tomato, garlic, cumin, and parsley.', 'Mediterranean-inspired', 'Plant-based', 'beginner', 10, 30, 4, '/images/misir-wat.jpg', 'Simmering canned tomatoes reduces excess liquid and concentrates their flavor.', 'Use clean utensils and refrigerate leftovers promptly.', '{"note":"No numeric nutrition estimate is provided; portions and brands vary. This content is educational, not medical advice."}', 'published'),
  ('Ginger Chicken Rice Bowl', 'ginger-chicken-rice-bowl', 'Ginger-soy chicken served over rice with wilted spinach.', 'East Asian-inspired', 'Quick meals', 'intermediate', 20, 25, 4, '/images/chicken-stir-fry.jpg', 'Cutting ingredients to similar sizes helps them cook at a more even rate.', 'Keep raw chicken separate and verify it reaches 74 C / 165 F with a food thermometer.', '{"note":"No numeric nutrition estimate is provided; portions and brands vary. This content is educational, not medical advice."}', 'published'),
  ('Spinach and Tomato Frittata', 'spinach-tomato-frittata', 'Eggs baked with spinach, tomato, and a little hard cheese.', 'Italian-inspired', 'Vegetarian', 'beginner', 12, 22, 4, '/images/shakshuka.jpg', 'A frittata sets gently when cooked over moderate heat and finished until the center is firm.', 'Cook egg dishes until fully set; refrigerate leftovers promptly.', '{"note":"No numeric nutrition estimate is provided; portions and brands vary. This content is educational, not medical advice."}', 'published');

insert into public.recipe_ingredients (recipe_id, ingredient_id, quantity, unit, is_optional, preparation_note)
select r.id, i.id, x.quantity, x.unit, x.is_optional, x.preparation_note
from (values
  ('ethiopian-misir-wat', 'red-onion', 2, 'medium', false, 'thinly sliced'),
  ('ethiopian-misir-wat', 'garlic', 3, 'cloves', false, 'minced'),
  ('ethiopian-misir-wat', 'berbere-spice-blend', 2, 'tablespoons', false, null),
  ('ethiopian-misir-wat', 'red-lentils', 1.5, 'cups', false, 'sorted and rinsed'),
  ('ethiopian-misir-wat', 'olive-oil', 2, 'tablespoons', false, null),
  ('ethiopian-misir-wat', 'vegetable-stock', 4, 'cups', false, 'or water'),
  ('skillet-shakshuka', 'red-onion', 1, 'medium', false, 'diced'),
  ('skillet-shakshuka', 'red-bell-pepper', 1, 'medium', false, 'diced'),
  ('skillet-shakshuka', 'garlic', 2, 'cloves', false, 'minced'),
  ('skillet-shakshuka', 'ground-cumin', 1, 'teaspoon', false, null),
  ('skillet-shakshuka', 'canned-tomatoes', 1, 'can', false, 'about 400 g'),
  ('skillet-shakshuka', 'eggs', 4, 'large', false, 'cracked into the sauce'),
  ('skillet-shakshuka', 'flat-leaf-parsley', 2, 'tablespoons', true, 'chopped for serving'),
  ('lemony-lentil-soup', 'green-lentils', 1, 'cup', false, 'sorted and rinsed'),
  ('lemony-lentil-soup', 'carrots', 2, 'medium', false, 'diced'),
  ('lemony-lentil-soup', 'red-onion', 1, 'medium', false, 'diced'),
  ('lemony-lentil-soup', 'garlic', 2, 'cloves', false, 'minced'),
  ('lemony-lentil-soup', 'vegetable-stock', 5, 'cups', false, null),
  ('lemony-lentil-soup', 'lemons', 1, 'large', false, 'juice to taste'),
  ('lemony-lentil-soup', 'flat-leaf-parsley', 2, 'tablespoons', true, 'chopped'),
  ('ginger-chicken-stir-fry', 'chicken-thighs', 500, 'g', false, 'cut into bite-size pieces'),
  ('ginger-chicken-stir-fry', 'fresh-ginger', 1, 'tablespoon', false, 'finely grated'),
  ('ginger-chicken-stir-fry', 'garlic', 2, 'cloves', false, 'minced'),
  ('ginger-chicken-stir-fry', 'red-bell-pepper', 1, 'large', false, 'sliced'),
  ('ginger-chicken-stir-fry', 'soy-sauce', 2, 'tablespoons', false, 'check allergen label'),
  ('ginger-chicken-stir-fry', 'basmati-rice', 1.5, 'cups', false, 'uncooked'),
  ('roasted-vegetable-pasta', 'dried-pasta', 350, 'g', false, 'any short shape'),
  ('roasted-vegetable-pasta', 'courgette', 2, 'medium', false, 'cut into half-moons'),
  ('roasted-vegetable-pasta', 'ripe-tomatoes', 3, 'medium', false, 'quartered'),
  ('roasted-vegetable-pasta', 'olive-oil', 2, 'tablespoons', false, null),
  ('roasted-vegetable-pasta', 'fresh-basil', 1, 'small bunch', false, 'torn at the end'),
  ('coconut-chickpea-curry', 'chickpeas', 2, 'cans', false, 'drained and rinsed'),
  ('coconut-chickpea-curry', 'coconut-milk', 1, 'can', false, 'about 400 ml'),
  ('coconut-chickpea-curry', 'canned-tomatoes', 1, 'can', false, 'about 400 g'),
  ('coconut-chickpea-curry', 'ground-cumin', 1, 'teaspoon', false, null),
  ('coconut-chickpea-curry', 'baby-spinach', 3, 'cups', false, 'washed if needed'),
  ('coconut-chickpea-curry', 'basmati-rice', 1.5, 'cups', false, 'uncooked'),
  ('green-lentil-herb-salad', 'green-lentils', 1, 'cup', false, 'sorted and rinsed'),
  ('green-lentil-herb-salad', 'ripe-tomatoes', 2, 'medium', false, 'diced'),
  ('green-lentil-herb-salad', 'red-onion', 0.5, 'medium', false, 'finely diced'),
  ('green-lentil-herb-salad', 'lemons', 1, 'large', false, 'juice to taste'),
  ('green-lentil-herb-salad', 'flat-leaf-parsley', 0.5, 'cup', false, 'chopped'),
  ('tomato-chickpea-stew', 'chickpeas', 2, 'cans', false, 'drained and rinsed'),
  ('tomato-chickpea-stew', 'canned-tomatoes', 1, 'can', false, 'about 400 g'),
  ('tomato-chickpea-stew', 'garlic', 3, 'cloves', false, 'minced'),
  ('tomato-chickpea-stew', 'ground-cumin', 1, 'teaspoon', false, null),
  ('tomato-chickpea-stew', 'olive-oil', 1, 'tablespoon', false, null),
  ('tomato-chickpea-stew', 'flat-leaf-parsley', 2, 'tablespoons', true, 'chopped for serving'),
  ('ginger-chicken-rice-bowl', 'chicken-thighs', 500, 'g', false, 'cut into bite-size pieces'),
  ('ginger-chicken-rice-bowl', 'fresh-ginger', 1, 'tablespoon', false, 'grated'),
  ('ginger-chicken-rice-bowl', 'soy-sauce', 2, 'tablespoons', false, 'check allergen label'),
  ('ginger-chicken-rice-bowl', 'basmati-rice', 1.5, 'cups', false, 'uncooked'),
  ('ginger-chicken-rice-bowl', 'baby-spinach', 3, 'cups', false, 'washed if needed'),
  ('spinach-tomato-frittata', 'eggs', 6, 'large', false, 'beaten'),
  ('spinach-tomato-frittata', 'baby-spinach', 2, 'cups', false, 'washed if needed'),
  ('spinach-tomato-frittata', 'ripe-tomatoes', 1, 'medium', false, 'diced'),
  ('spinach-tomato-frittata', 'red-onion', 0.5, 'medium', false, 'finely diced'),
  ('spinach-tomato-frittata', 'hard-cheese', 0.25, 'cup', true, 'finely grated'),
  ('spinach-tomato-frittata', 'olive-oil', 1, 'tablespoon', false, null)
) as x(recipe_slug, ingredient_slug, quantity, unit, is_optional, preparation_note)
join public.recipes r on r.slug = x.recipe_slug
join public.ingredients i on i.slug = x.ingredient_slug;

insert into public.recipe_steps (recipe_id, step_number, instruction, time_minutes, educational_note)
select r.id, x.step_number, x.instruction, x.time_minutes, x.educational_note
from (values
  ('ethiopian-misir-wat', 1, 'Warm the oil in a heavy pot over medium-low heat. Add the onion and cook, stirring, until soft and translucent.', 10, 'Moderate heat helps onions soften without scorching.'),
  ('ethiopian-misir-wat', 2, 'Add garlic and berbere and stir briefly until fragrant.', 1, 'Spices release aroma in warm oil; lower the heat if they begin to darken quickly.'),
  ('ethiopian-misir-wat', 3, 'Stir in rinsed red lentils and vegetable stock. Bring to a gentle simmer.', 5, 'Rinsing removes loose dust; split red lentils do not need soaking.'),
  ('ethiopian-misir-wat', 4, 'Simmer, stirring occasionally, until the lentils are soft and the stew is thick. Add a little water if needed.', 30, 'Cooking time varies with lentil age and simmer strength.'),
  ('skillet-shakshuka', 1, 'Warm oil in a wide skillet. Soften the onion and pepper over medium heat.', 8, 'Cut vegetables evenly so they soften at a similar rate.'),
  ('skillet-shakshuka', 2, 'Add garlic and cumin and stir until fragrant, then add canned tomatoes.', 2, 'Avoid browning garlic deeply, which can make it bitter.'),
  ('skillet-shakshuka', 3, 'Simmer until the sauce thickens. Make small wells and add the eggs.', 10, 'A thicker sauce helps hold the eggs in place.'),
  ('skillet-shakshuka', 4, 'Cover and cook gently until the egg whites are fully set. Finish with parsley.', 7, 'Use pasteurized eggs for any variation served with a runny center.'),
  ('lemony-lentil-soup', 1, 'Rinse the lentils. Warm a little oil in a pot and soften the onion and carrots.', 8, 'Aromatic vegetables create a savory base before liquid is added.'),
  ('lemony-lentil-soup', 2, 'Add garlic and stir briefly, then add lentils and vegetable stock.', 2, 'Keep garlic moving so it does not scorch.'),
  ('lemony-lentil-soup', 3, 'Bring to a simmer and cook until lentils are tender.', 30, 'Keep the simmer gentle and add water if the soup becomes thicker than desired.'),
  ('lemony-lentil-soup', 4, 'Stir in lemon juice and parsley, then season to taste.', 2, 'Adding acidity at the end preserves its bright flavor.'),
  ('ginger-chicken-stir-fry', 1, 'Cook the rice according to its package instructions. Prepare and separate the raw chicken from vegetables.', 15, 'Use separate boards or wash and sanitize surfaces after raw poultry.'),
  ('ginger-chicken-stir-fry', 2, 'Heat a wide pan. Cook chicken in batches until browned and fully cooked.', 10, 'Do not overcrowd the pan; verify chicken reaches 74 C / 165 F with a thermometer.'),
  ('ginger-chicken-stir-fry', 3, 'Add pepper, ginger, and garlic. Stir-fry until the pepper is crisp-tender.', 4, 'Adding quick-cooking aromatics later helps prevent burning.'),
  ('ginger-chicken-stir-fry', 4, 'Return chicken to the pan, add soy sauce, and stir until hot. Serve with rice.', 2, 'Check condiment labels for allergens such as soy and wheat.'),
  ('roasted-vegetable-pasta', 1, 'Heat the oven to 220 C / 425 F. Toss courgette and tomatoes with olive oil and spread on a tray.', 5, 'A single layer encourages browning instead of steaming.'),
  ('roasted-vegetable-pasta', 2, 'Roast the vegetables until tender and lightly browned.', 20, 'Turn pieces once if the tray browns unevenly.'),
  ('roasted-vegetable-pasta', 3, 'Boil the pasta in salted water according to package instructions, then drain.', 12, 'Reserve a small cup of pasta water before draining if you want a looser sauce.'),
  ('roasted-vegetable-pasta', 4, 'Toss pasta with vegetables and torn basil. Adjust seasoning and serve.', 2, 'Fresh herbs keep more aroma when added near the end.'),
  ('coconut-chickpea-curry', 1, 'Cook the rice according to package instructions. Warm oil in a saucepan.', 15, 'Prepare longer-cooking rice first so it is ready with the curry.'),
  ('coconut-chickpea-curry', 2, 'Add cumin and stir briefly over moderate heat until fragrant.', 1, 'Spices should smell aromatic, not burnt.'),
  ('coconut-chickpea-curry', 3, 'Add tomatoes, coconut milk, and rinsed chickpeas. Simmer until the sauce thickens.', 20, 'A gentle simmer helps the sauce reduce without scorching.'),
  ('coconut-chickpea-curry', 4, 'Fold in spinach until wilted. Serve with rice.', 3, 'Add tender greens at the end to preserve their texture.'),
  ('green-lentil-herb-salad', 1, 'Rinse green lentils, cover with water, and simmer until tender but still holding their shape.', 25, 'Check texture near the end because cooking time varies.'),
  ('green-lentil-herb-salad', 2, 'Drain lentils and spread them in a shallow dish to cool promptly.', 10, 'Shallow layers cool more quickly than a deep pot.'),
  ('green-lentil-herb-salad', 3, 'Combine lentils with tomato, onion, and parsley.', 5, 'Cut ingredients into similar sizes for an even bite.'),
  ('green-lentil-herb-salad', 4, 'Dress with lemon and olive oil. Keep chilled until serving.', 2, 'Taste and adjust acidity gradually.'),
  ('tomato-chickpea-stew', 1, 'Warm olive oil in a saucepan and soften the garlic briefly.', 2, 'Use moderate heat so the garlic remains pale and fragrant.'),
  ('tomato-chickpea-stew', 2, 'Add cumin and tomatoes. Simmer until the tomato base thickens.', 15, 'Reduction concentrates flavor by allowing water to evaporate.'),
  ('tomato-chickpea-stew', 3, 'Stir in drained chickpeas and simmer until hot throughout.', 10, 'Rinsing canned chickpeas can reduce excess brine.'),
  ('tomato-chickpea-stew', 4, 'Finish with parsley and serve warm.', 1, 'Fresh herbs are most aromatic when added just before serving.'),
  ('ginger-chicken-rice-bowl', 1, 'Cook rice according to its package directions and prepare vegetables.', 15, 'Keep raw chicken and ready-to-eat ingredients separate.'),
  ('ginger-chicken-rice-bowl', 2, 'Cook chicken in a hot pan until browned and its center reaches 74 C / 165 F.', 10, 'A food thermometer is more reliable than color for checking poultry doneness.'),
  ('ginger-chicken-rice-bowl', 3, 'Add ginger and soy sauce, then stir until the chicken is coated and hot.', 2, 'Check labels for soy and wheat allergens.'),
  ('ginger-chicken-rice-bowl', 4, 'Wilt spinach in the pan and serve the chicken over rice.', 3, 'Spinach cooks quickly from residual heat.'),
  ('spinach-tomato-frittata', 1, 'Heat the oven to 190 C / 375 F. Soften onion in an oven-safe skillet.', 5, 'A moderate oven helps eggs set without toughening too quickly.'),
  ('spinach-tomato-frittata', 2, 'Add spinach and tomato and cook until the spinach wilts.', 3, 'Remove excess moisture if the tomatoes release a lot of liquid.'),
  ('spinach-tomato-frittata', 3, 'Pour in beaten eggs and sprinkle with cheese if using. Cook briefly on the stovetop.', 3, 'Move cooked egg from the edge toward the center for even setting.'),
  ('spinach-tomato-frittata', 4, 'Bake until the center is fully set. Rest briefly before slicing.', 12, 'Egg dishes should be cooked through; oven times vary by pan and depth.')
) as x(recipe_slug, step_number, instruction, time_minutes, educational_note)
join public.recipes r on r.slug = x.recipe_slug;

insert into public.learning_modules (title, slug, description, category, difficulty, content, status)
values
  ('Red lentils and the texture they make', 'red-lentils-and-texture', 'Learn why split red lentils soften quickly and how that changes soups and stews.', 'ingredients', 'beginner', '{"sections":[{"heading":"Split and whole lentils differ","body":"Red lentils are commonly sold split and often hulled. They soften faster than many whole lentils and can thicken the liquid around them."},{"heading":"Rinse and simmer","body":"Sort and rinse dry lentils, then simmer gently until tender. Older lentils and local growing conditions can change cooking time."}]}', 'published'),
  ('Season aromatics in a pan', 'season-aromatics-in-a-pan', 'Build flavor with onions, garlic, and spices while managing heat carefully.', 'techniques', 'beginner', '{"sections":[{"heading":"Start with the slower ingredients","body":"Onions usually need more time to soften than minced garlic. Add garlic later so it releases aroma without scorching."},{"heading":"Bloom spices gently","body":"Brief contact with warm oil can release spice aromas. Keep the heat moderate and add liquid if spices darken too quickly."}]}', 'published'),
  ('Choose and use a chef knife', 'choose-and-use-a-chef-knife', 'Understand a chef knife shape, a stable board, and controlled cutting habits.', 'tools', 'beginner', '{"sections":[{"heading":"Choose a comfortable tool","body":"A chef knife should feel controllable in your hand. Keep it sharp and use it only for foods suited to the blade."},{"heading":"Stabilize before cutting","body":"Place a damp towel under a cutting board if it slides. Use a tucked-finger claw grip to guide food while keeping fingertips back."}]}', 'published'),
  ('Separate raw poultry and ready-to-eat food', 'separate-raw-poultry-and-ready-to-eat-food', 'Practice conservative habits that reduce cross-contamination when handling poultry.', 'food_safety', 'beginner', '{"sections":[{"heading":"Keep raw poultry separate","body":"Use a dedicated board or plate for raw poultry. Keep its juices away from ready-to-eat food, then wash hands, tools, and surfaces with soap and hot water."},{"heading":"Check doneness with a thermometer","body":"Cook poultry to 74 C / 165 F measured in the thickest part with a food thermometer. Do not rely on color alone, and do not wash raw chicken."}]}', 'published'),
  ('Build a balanced, satisfying plate', 'build-a-balanced-satisfying-plate', 'Explore how vegetables, grains, legumes, and other foods can bring variety to a meal.', 'nutrition', 'beginner', '{"sections":[{"heading":"Think about variety","body":"Combining vegetables or fruit, grains or other starches, and protein foods can add a range of flavors and textures. Needs differ from person to person."},{"heading":"Legumes do more than one job","body":"Beans, peas, and lentils contribute plant protein and dietary fiber. This is general food education, not individualized medical advice."}]}', 'published'),
  ('Berbere and the layers of misir wat', 'berbere-and-the-layers-of-misir-wat', 'Explore berbere spice blends and the lentil technique behind Ethiopian misir wat.', 'world_cuisine', 'intermediate', '{"sections":[{"heading":"Berbere blends vary","body":"Berbere is a complex Ethiopian spice blend. Ingredients, proportions, and heat vary among makers and households; check the blend label before serving."},{"heading":"Build the stew patiently","body":"Misir wat commonly combines lentils with aromatics and seasoned oil. Gentle cooking lets split lentils soften and thicken the stew."}]}', 'published');

insert into public.questions (slug, learning_module_id, question_text, question_type, explanation, difficulty, status)
select x.slug, m.id, x.question_text, 'multiple_choice', x.explanation, x.difficulty::public.difficulty_level, 'published'
from (values
  ('red-lentils-texture', 'red-lentils-and-texture', 'What texture do split red lentils often create when fully simmered?', 'They soften and can thicken the surrounding liquid.', 'beginner'),
  ('rinse-dry-lentils', 'red-lentils-and-texture', 'What is a sensible first step before cooking dry lentils?', 'Sort and rinse them, then follow a suitable cooking method.', 'beginner'),
  ('older-lentils-time', 'red-lentils-and-texture', 'Why might two batches of lentils need different cooking times?', 'Age, variety, and growing conditions can affect how quickly they soften.', 'intermediate'),
  ('aromatics-order', 'season-aromatics-in-a-pan', 'When is minced garlic commonly added when softening onions?', 'After the onions have started to soften, so the garlic is less likely to scorch.', 'beginner'),
  ('spice-bloom', 'season-aromatics-in-a-pan', 'What does briefly warming spices in oil help do?', 'Release aromatic compounds while the cook watches carefully for scorching.', 'beginner'),
  ('scorched-spices', 'season-aromatics-in-a-pan', 'What should you do if spices begin to darken too quickly?', 'Lower the heat and add other ingredients or liquid as appropriate.', 'intermediate'),
  ('cutting-board-stable', 'choose-and-use-a-chef-knife', 'How can you help stop a cutting board sliding on a counter?', 'Place a damp towel beneath it and check that it is stable.', 'beginner'),
  ('knife-claw-grip', 'choose-and-use-a-chef-knife', 'What is the purpose of a tucked-finger claw grip?', 'It helps guide food while keeping fingertips back from the blade.', 'beginner'),
  ('knife-sharp-care', 'choose-and-use-a-chef-knife', 'Which knife habit supports controlled cutting?', 'Keep the blade sharp and use a stable board with controlled strokes.', 'intermediate'),
  ('raw-poultry-separation', 'separate-raw-poultry-and-ready-to-eat-food', 'How should raw poultry be handled around ready-to-eat foods?', 'Keep it separate and use dedicated or thoroughly cleaned utensils and surfaces.', 'beginner'),
  ('poultry-temperature', 'separate-raw-poultry-and-ready-to-eat-food', 'What internal temperature should poultry reach according to the module?', '74 C / 165 F measured with a food thermometer.', 'beginner'),
  ('wash-raw-chicken', 'separate-raw-poultry-and-ready-to-eat-food', 'Should raw chicken be rinsed in the sink before cooking?', 'No. Rinsing can spread droplets; cook it safely and clean hands and surfaces.', 'beginner'),
  ('poultry-doneness-color', 'separate-raw-poultry-and-ready-to-eat-food', 'Why is color alone not a reliable check for poultry doneness?', 'Appearance can vary; a thermometer checks internal temperature directly.', 'intermediate'),
  ('wash-hands-raw-poultry', 'separate-raw-poultry-and-ready-to-eat-food', 'What should you do after handling raw poultry?', 'Wash hands and clean tools and surfaces before handling ready-to-eat food.', 'beginner'),
  ('lentils-cooling', 'separate-raw-poultry-and-ready-to-eat-food', 'How can cooked food be cooled more quickly before refrigeration?', 'Divide it into shallow containers rather than leaving it in a deep pot.', 'intermediate'),
  ('meal-variety', 'build-a-balanced-satisfying-plate', 'What is one practical reason to include a variety of foods in a meal?', 'Different foods can contribute different flavors, textures, and nutrients.', 'beginner'),
  ('legumes-fiber', 'build-a-balanced-satisfying-plate', 'What are lentils commonly known to contribute?', 'Plant protein and dietary fiber.', 'beginner'),
  ('nutrition-individual', 'build-a-balanced-satisfying-plate', 'Should general nutrition learning replace individualized medical advice?', 'No. It is general education and personal needs can differ.', 'beginner'),
  ('plate-rigidity', 'build-a-balanced-satisfying-plate', 'Is there one exact plate composition suitable for every person and context?', 'No. Needs, preferences, and circumstances differ.', 'intermediate'),
  ('whole-food-variety', 'build-a-balanced-satisfying-plate', 'Which approach best describes building a satisfying meal?', 'Consider variety and balance while adapting to the people eating it.', 'beginner'),
  ('berbere-variation', 'berbere-and-the-layers-of-misir-wat', 'Which statement about berbere is most accurate?', 'It is a spice blend whose ingredients and heat can vary by maker and household.', 'beginner'),
  ('misir-wat-lentils', 'berbere-and-the-layers-of-misir-wat', 'Which ingredient is central to misir wat?', 'Lentils simmered with aromatics and seasoning.', 'beginner'),
  ('ethiopian-context', 'berbere-and-the-layers-of-misir-wat', 'How should a learner approach a dish from a food tradition?', 'Learn its ingredients and context while recognizing that practices vary.', 'intermediate'),
  ('blend-label', 'berbere-and-the-layers-of-misir-wat', 'Why check the label on a purchased spice blend?', 'Ingredients and chili heat vary, and the label may identify allergens.', 'beginner'),
  ('injera-context', 'berbere-and-the-layers-of-misir-wat', 'Which grain is commonly associated with injera in Ethiopian cooking?', 'Teff is commonly used, though preparations and ingredients can vary.', 'intermediate'),
  ('oil-medium-heat', 'season-aromatics-in-a-pan', 'Why use moderate heat when first adding spices to oil?', 'It gives aromas time to release and reduces the chance of burning.', 'beginner'),
  ('stir-fry-batches', 'season-aromatics-in-a-pan', 'Why cook a crowded stir-fry in batches?', 'Crowding can lower pan heat and encourage ingredients to steam.', 'intermediate'),
  ('knife-cut-consistency', 'choose-and-use-a-chef-knife', 'Why cut vegetables into pieces of similar size?', 'Similar sizes tend to cook at a more similar rate.', 'beginner'),
  ('food-thermometer', 'separate-raw-poultry-and-ready-to-eat-food', 'Where should you measure the temperature of a large poultry piece?', 'In the thickest part, avoiding bone where possible.', 'intermediate'),
  ('flavor-acidity', 'build-a-balanced-satisfying-plate', 'What can a little lemon juice do in a lentil dish?', 'Its acidity can brighten flavor; add gradually and taste.', 'beginner')
) as x(slug, module_slug, question_text, explanation, difficulty)
join public.learning_modules m on m.slug = x.module_slug;

insert into public.question_options (question_id, option_text, option_order, is_correct)
select q.id, x.option_text, x.option_order, x.is_correct
from (values
  ('red-lentils-texture', 1, 'They soften and can thicken the surrounding liquid.', true),
  ('red-lentils-texture', 2, 'They stay crunchy even after a long simmer.', false),
  ('red-lentils-texture', 3, 'They turn into whole beans with firm skins.', false),
  ('red-lentils-texture', 4, 'They dissolve only when fried without liquid.', false),
  ('rinse-dry-lentils', 1, 'Sort and rinse them, then follow a suitable cooking method.', true),
  ('rinse-dry-lentils', 2, 'Leave them soaking in oil overnight.', false),
  ('rinse-dry-lentils', 3, 'Wash them with soap before cooking.', false),
  ('rinse-dry-lentils', 4, 'Eat them dry to preserve texture.', false),
  ('older-lentils-time', 1, 'Age, variety, and growing conditions can affect how quickly they soften.', true),
  ('older-lentils-time', 2, 'Every lentil batch always cooks in exactly the same time.', false),
  ('older-lentils-time', 3, 'The pot color determines the cooking time.', false),
  ('older-lentils-time', 4, 'Only salt determines whether lentils become tender.', false),
  ('aromatics-order', 1, 'After the onions have started to soften, so the garlic is less likely to scorch.', true),
  ('aromatics-order', 2, 'Before heating the pan, then leave it unattended.', false),
  ('aromatics-order', 3, 'After the dish has finished cooking.', false),
  ('aromatics-order', 4, 'Only after the garlic has turned dark brown.', false),
  ('spice-bloom', 1, 'Release aromatic compounds while the cook watches carefully for scorching.', true),
  ('spice-bloom', 2, 'Make every spice taste identical.', false),
  ('spice-bloom', 3, 'Remove all aroma from spices.', false),
  ('spice-bloom', 4, 'Replace the need to cook the rest of the dish.', false),
  ('scorched-spices', 1, 'Lower the heat and add other ingredients or liquid as appropriate.', true),
  ('scorched-spices', 2, 'Increase the heat and stop stirring.', false),
  ('scorched-spices', 3, 'Add dry paper to the pan.', false),
  ('scorched-spices', 4, 'Leave the pan unattended until smoke clears.', false),
  ('cutting-board-stable', 1, 'Place a damp towel beneath it and check that it is stable.', true),
  ('cutting-board-stable', 2, 'Balance it on a curved bowl.', false),
  ('cutting-board-stable', 3, 'Hold it in the air while cutting.', false),
  ('cutting-board-stable', 4, 'Add loose flour underneath it.', false),
  ('knife-claw-grip', 1, 'It helps guide food while keeping fingertips back from the blade.', true),
  ('knife-claw-grip', 2, 'It keeps fingertips extended over the blade.', false),
  ('knife-claw-grip', 3, 'It replaces the need for a cutting board.', false),
  ('knife-claw-grip', 4, 'It makes every cut happen automatically.', false),
  ('knife-sharp-care', 1, 'Keep the blade sharp and use a stable board with controlled strokes.', true),
  ('knife-sharp-care', 2, 'Use a loose board and force a dull knife through food.', false),
  ('knife-sharp-care', 3, 'Store the knife loose in a sink of water.', false),
  ('knife-sharp-care', 4, 'Use the knife for tasks the blade is not designed for.', false),
  ('raw-poultry-separation', 1, 'Keep it separate and use dedicated or thoroughly cleaned utensils and surfaces.', true),
  ('raw-poultry-separation', 2, 'Place it beside salad on the same unwashed board.', false),
  ('raw-poultry-separation', 3, 'Rinse it over ready-to-eat produce.', false),
  ('raw-poultry-separation', 4, 'Use the same plate for cooked chicken without washing it.', false),
  ('poultry-temperature', 1, '74 C / 165 F measured with a food thermometer.', true),
  ('poultry-temperature', 2, '50 C / 122 F measured at the pan handle.', false),
  ('poultry-temperature', 3, 'Temperature does not matter if the outside is browned.', false),
  ('poultry-temperature', 4, 'Room temperature measured before cooking.', false),
  ('wash-raw-chicken', 1, 'No. Rinsing can spread droplets; cook it safely and clean hands and surfaces.', true),
  ('wash-raw-chicken', 2, 'Yes. Rinse it vigorously beside clean dishes.', false),
  ('wash-raw-chicken', 3, 'Yes. Soap should be applied to the meat.', false),
  ('wash-raw-chicken', 4, 'Only if the sink is full of other food.', false),
  ('poultry-doneness-color', 1, 'Appearance can vary; a thermometer checks internal temperature directly.', true),
  ('poultry-doneness-color', 2, 'All cooked poultry always looks the same shade.', false),
  ('poultry-doneness-color', 3, 'The pan sound confirms the center temperature.', false),
  ('poultry-doneness-color', 4, 'Color is always a precise temperature measurement.', false),
  ('wash-hands-raw-poultry', 1, 'Wash hands and clean tools and surfaces before handling ready-to-eat food.', true),
  ('wash-hands-raw-poultry', 2, 'Wipe hands on an apron and continue.', false),
  ('wash-hands-raw-poultry', 3, 'Rinse hands without soap for one second.', false),
  ('wash-hands-raw-poultry', 4, 'Handle salad first with the same gloves.', false),
  ('lentils-cooling', 1, 'Divide it into shallow containers rather than leaving it in a deep pot.', true),
  ('lentils-cooling', 2, 'Leave it uncovered on the counter overnight.', false),
  ('lentils-cooling', 3, 'Put a hot pot directly into a crowded refrigerator.', false),
  ('lentils-cooling', 4, 'Mix it with raw poultry.', false),
  ('meal-variety', 1, 'Different foods can contribute different flavors, textures, and nutrients.', true),
  ('meal-variety', 2, 'Only one food can ever be part of a satisfying meal.', false),
  ('meal-variety', 3, 'Color alone determines whether a meal is balanced.', false),
  ('meal-variety', 4, 'Variety means every meal must be identical.', false),
  ('legumes-fiber', 1, 'Plant protein and dietary fiber.', true),
  ('legumes-fiber', 2, 'Only added refined sugar.', false),
  ('legumes-fiber', 3, 'No nutrients of any kind.', false),
  ('legumes-fiber', 4, 'A guaranteed medical treatment.', false),
  ('nutrition-individual', 1, 'No. It is general education and personal needs can differ.', true),
  ('nutrition-individual', 2, 'Yes. General lessons replace a clinician.', false),
  ('nutrition-individual', 3, 'Yes. The same diet is suitable for everyone.', false),
  ('nutrition-individual', 4, 'No. Nutrition cannot be discussed educationally.', false),
  ('plate-rigidity', 1, 'No. Needs, preferences, and circumstances differ.', true),
  ('plate-rigidity', 2, 'Yes. One exact plate works for all people.', false),
  ('plate-rigidity', 3, 'Yes. Meals never depend on context.', false),
  ('plate-rigidity', 4, 'No. Food has no relationship to nutrition.', false),
  ('whole-food-variety', 1, 'Consider variety and balance while adapting to the people eating it.', true),
  ('whole-food-variety', 2, 'Follow one rigid rule regardless of context.', false),
  ('whole-food-variety', 3, 'Avoid all vegetables and grains.', false),
  ('whole-food-variety', 4, 'Choose food only by its color.', false),
  ('berbere-variation', 1, 'It is a spice blend whose ingredients and heat can vary by maker and household.', true),
  ('berbere-variation', 2, 'Every blend has one legally fixed recipe.', false),
  ('berbere-variation', 3, 'It is always mild and contains the same ingredients.', false),
  ('berbere-variation', 4, 'It is unrelated to food traditions in Ethiopia.', false),
  ('misir-wat-lentils', 1, 'Lentils simmered with aromatics and seasoning.', true),
  ('misir-wat-lentils', 2, 'Raw rice served without seasoning.', false),
  ('misir-wat-lentils', 3, 'A dish made only from fresh fruit.', false),
  ('misir-wat-lentils', 4, 'A type of knife technique.', false),
  ('ethiopian-context', 1, 'Learn its ingredients and context while recognizing that practices vary.', true),
  ('ethiopian-context', 2, 'Assume one recipe represents every household.', false),
  ('ethiopian-context', 3, 'Use stereotypes instead of asking how a dish is made.', false),
  ('ethiopian-context', 4, 'Ignore the ingredients and history.', false),
  ('blend-label', 1, 'Ingredients and chili heat vary, and the label may identify allergens.', true),
  ('blend-label', 2, 'Labels are never useful for food.', false),
  ('blend-label', 3, 'All spice blends contain identical ingredients.', false),
  ('blend-label', 4, 'A label guarantees no one has an allergy.', false),
  ('injera-context', 1, 'Teff is commonly used, though preparations and ingredients can vary.', true),
  ('injera-context', 2, 'Only wheat is used in every preparation.', false),
  ('injera-context', 3, 'Rice is always the only ingredient.', false),
  ('injera-context', 4, 'Injera is a kitchen tool.', false),
  ('oil-medium-heat', 1, 'It gives aromas time to release and reduces the chance of burning.', true),
  ('oil-medium-heat', 2, 'It makes spices impossible to burn.', false),
  ('oil-medium-heat', 3, 'It removes all flavor from the spices.', false),
  ('oil-medium-heat', 4, 'It means the pan should be left unattended.', false),
  ('stir-fry-batches', 1, 'Crowding can lower pan heat and encourage ingredients to steam.', true),
  ('stir-fry-batches', 2, 'A pan has no limit to how much it can cook evenly.', false),
  ('stir-fry-batches', 3, 'Smaller batches make food unsafe by definition.', false),
  ('stir-fry-batches', 4, 'Crowding guarantees crisp vegetables.', false),
  ('knife-cut-consistency', 1, 'Similar sizes tend to cook at a more similar rate.', true),
  ('knife-cut-consistency', 2, 'Size never affects cooking.', false),
  ('knife-cut-consistency', 3, 'Large pieces always cook faster than small pieces.', false),
  ('knife-cut-consistency', 4, 'Uniform cuts remove the need to check doneness.', false),
  ('food-thermometer', 1, 'In the thickest part, avoiding bone where possible.', true),
  ('food-thermometer', 2, 'Only on the outside surface.', false),
  ('food-thermometer', 3, 'Against the pan.', false),
  ('food-thermometer', 4, 'In a vegetable served beside it.', false),
  ('flavor-acidity', 1, 'Its acidity can brighten flavor; add gradually and taste.', true),
  ('flavor-acidity', 2, 'It makes every dish taste exactly the same.', false),
  ('flavor-acidity', 3, 'It replaces safe cooking temperatures.', false),
  ('flavor-acidity', 4, 'It prevents all food spoilage.', false)
) as x(question_slug, option_order, option_text, is_correct)
join public.questions q on q.slug = x.question_slug;

insert into public.achievements (name, slug, description, icon, requirement, status)
values
  ('Curious Taster', 'curious-taster', 'Explore your first published food lesson.', 'sparkles', '{"kind":"module_completions","count":1}', 'published'),
  ('Ingredient Explorer', 'ingredient-explorer', 'Study ingredient notes across several recipes.', 'apple', '{"kind":"ingredient_lessons","count":5}', 'published'),
  ('Knife Skills Starter', 'knife-skills-starter', 'Learn the foundations of safe, controlled knife work.', 'utensils', '{"kind":"module_slug","slug":"choose-and-use-a-chef-knife"}', 'published'),
  ('Flavor Builder', 'flavor-builder', 'Explore how aromatics and spices develop flavor.', 'flame', '{"kind":"module_slug","slug":"season-aromatics-in-a-pan"}', 'published'),
  ('Safety Minded', 'safety-minded', 'Review a food-safety lesson.', 'shield-check', '{"kind":"module_slug","slug":"separate-raw-poultry-and-ready-to-eat-food"}', 'published'),
  ('Recipe Reader', 'recipe-reader', 'Explore the educational notes in three recipes.', 'book-open', '{"kind":"recipe_views","count":3}', 'published'),
  ('Cuisine Storyteller', 'cuisine-storyteller', 'Study food context from multiple culinary traditions.', 'globe-2', '{"kind":"cuisine_modules","count":3}', 'published'),
  ('Steady Learner', 'steady-learner', 'Return to learning content on several separate days.', 'calendar-check', '{"kind":"learning_days","count":5}', 'published');

insert into public.daily_challenges (challenge_date, title, slug, description, challenge_type, recipe_id, learning_module_id, ingredient_id, status)
select x.challenge_date::date, x.title, x.slug, x.description, x.challenge_type::public.daily_challenge_type,
  r.id, m.id, i.id, 'published'
from (values
  ('2026-10-01', 'Find the gentle simmer', 'find-the-gentle-simmer-2026-10-01', 'Read the lentil method and identify why a gentle simmer helps preserve texture.', 'recipe', 'ethiopian-misir-wat', null, null),
  ('2026-10-02', 'Layer aromatics with care', 'layer-aromatics-with-care-2026-10-02', 'Review when garlic is added and how to keep spices from scorching.', 'learning_module', null, 'season-aromatics-in-a-pan', null),
  ('2026-10-03', 'Know your lentils', 'know-your-lentils-2026-10-03', 'Compare split red lentils with whole green lentils and their cooking textures.', 'ingredient', null, null, 'red-lentils'),
  ('2026-10-04', 'Build the tomato base', 'build-the-tomato-base-2026-10-04', 'Explore how a tomato sauce thickens before eggs are added.', 'recipe', 'skillet-shakshuka', null, null),
  ('2026-10-05', 'Separate and check', 'separate-and-check-2026-10-05', 'Review separate preparation for raw poultry and use a thermometer for doneness.', 'learning_module', null, 'separate-raw-poultry-and-ready-to-eat-food', null)
) as x(challenge_date, title, slug, description, challenge_type, recipe_slug, module_slug, ingredient_slug)
left join public.recipes r on r.slug = x.recipe_slug
left join public.learning_modules m on m.slug = x.module_slug
left join public.ingredients i on i.slug = x.ingredient_slug;
